export const DOCUMENT_LIST_REQUEST = 'DOCUMENT_LIST_REQUEST'
export const DOCUMENT_LIST_SUCCESS = 'DOCUMENT_LIST_SUCCESS'
export const DOCUMENT_LIST_FAIL = 'DOCUMENT_LIST_FAIL'

export const DOCUMENT_DETAILS_REQUEST = 'DOCUMENT_DETAILS_REQUEST'
export const DOCUMENT_DETAILS_SUCCESS = 'DOCUMENT_DETAILS_SUCCESS'
export const DOCUMENT_DETAILS_FAIL = 'DOCUMENT_DETAILS_FAIL'